# Travis configuration file for HyperBuffer
language:
    - cpp
matrix:
    include:
        - os: osx
          dist: trusty
          osx_image: xcode11.3
          compiler: clang
          env:
            - COMPILER="clang++"
            - C_COMPILER="clang"
            - EXTRA_CXX_FLAGS="-stdlib=libc++"
          
        - os: linux
          dist: bionic
          compiler: gcc
          
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7']
          env:
            - COMPILER="g++-7"
            - C_COMPILER="gcc-7"
            - EXTRA_CXX_FLAGS=""
            
        - os: windows
          env: MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
           
before_script:
    # Export CXX to tell cmake which compiler to use
    - export CXX=${COMPILER}
    - export C=${C_COMPILER}
    - export CPP_STANDARD=14
    # Check versions
    - cmake --version
    # Run your build commands next
    - cd deploy
    - mkdir -p build
    - cd build
    - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake -H. -j 2 ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="${EXTRA_CXX_FLAGS}"; fi
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then export PATH=$MSBUILD_PATH:$PATH; cmake -G "Visual Studio 15 2017" -DCMAKE_GENERATOR_PLATFORM=x64 ../..; fi
    
script:
    - |
      if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
          cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64
          cmd.exe //C "MSBuild.exe MemorySentinel.sln" //m:2 //nologo //verbosity:quiet //p:Configuration=Debug //p:Platform=x64
          ./Debug/MemorySentinelTest.exe
      else
          make -j 2
          ./MemorySentinelTest
      fi
    

    
