# Travis configuration file for HyperBuffer
language:
    - cpp
matrix:
    include:
        - os: osx
          dist: trusty
          osx_image: xcode11.3
          compiler: clang
          env: - COMPILER='clang++'
               - C_COMPILER='clang'
               - EXTRA_CXX_FLAGS="-stdlib=libc++"
          
        - os: linux
          dist: bionic
          compiler: gcc
          
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7']
          env: - COMPILER='g++-7'
               - C_COMPILER='gcc-7'
               - EXTRA_CXX_FLAGS="-stdlib=libc++"
         
before_script:
    # Export CXX to tell cmake which compiler to use
    - export CXX=${COMPILER}
    - export C=${C_COMPILER}
    - export CPP_STANDARD=14
    # Check versions
    - cmake --version
    # Run your build commands next
    - cd deploy
    - mkdir -p build
    - cd build
    - cmake -H. -j 2 ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=${EXTRA_FLAGS} ${EXTRA_CXX_FLAGS}
    
script:
    - make -j 2
    - ./MemorySentinelTest
    
