name: Sidelobe Build Matrix macos
on:
  workflow_call:
jobs:
  build:
    name: ${{matrix.os}}, ${{matrix.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        cxx:
          - clang++
        build_type: [Debug]
        std: [14]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup & Cmake
      working-directory: deploy
      env:
        CXX: ${{matrix.cxx}}
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              ../..
        
    - name: Build & Run Tests
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      working-directory: deploy/build
      run: |
        cmake --build . --parallel 2 --target MemorySentinelTest
        ctest -C ${{ matrix.build_type }} -L MemorySentinelTest -j 2
